--Create table user in database
CREATE TABLE user(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	isAdmin BOOLEAN DEFAULT 0
);